print(f'NFC West       W   L  T')
print(f'-----------------------')
print(f'Seattle        13  3  0')
print(f'San Francisco  12  4  0')
print(f'Arizona        10  6  0')
print(f'St. Louis      7   9  0')
print(f'')
print(f'NFC North      W   L  T')
print(f'-----------------------')
print(f'Green Bay      8   7  1')
print(f'Chicago        8   8  0')
print(f'Detroit        7   9  0')
print(f'Minnesota      5  10  1')
